name: 'Run actions'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true
    - run: npm install

    - name: Run tests
      run: npm run test

    - uses: tintef/nyc-reporter-action@0.0.7
      if: ${{ github.event_name == 'pull_request' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
